### PR TITLE
Rate limit event handler

### PR DESCRIPTION
**Pull request by marcogruhl**
Added an event for every request which returns the rate limit using an `EventHandler`.
It uses the ResponseHeaders described at: [Twitter API Documentation](https://developer.twitter.com/en/docs/twitter-api/rate-limits#headers-and-codes)

### CODE REVIEW

**Comment by marcogruhl** [comment]
Based on Discussion #11

**Comment by Xwilarg** [comment]
Looks like the tests are failing, not sure if it's your changes or just that GitHub secrets are not available in PRs, was it working in your side?
Would also be nice if you could solve the Codacy issues: https://github.com/Xwilarg/TwitterSharp/pull/14/checks?check_run_id=4931058551

**Comment by marcogruhl** [comment]
All tests are passing at my side. i adopted your method using an environment variable. The logs indicate the problem is with authorization. I dont know how to fix this in the git environment. But it must be there before.
I also fixed the codacy issues.

**Comment by Xwilarg** [comment]
I'll be busy today so I'll check all of that this evening

**Comment by marcogruhl** [comment]
> Looks like the tests are failing, not sure if it's your changes or just that GitHub secrets are not available in PRs, was it working in your side? Would also be nice if you could solve the Codacy issues: https://github.com/Xwilarg/TwitterSharp/pull/14/checks?check_run_id=4931058551

I look at the other pull request and it has the same "problem" : [test fail](https://github.com/Xwilarg/TwitterSharp/runs/2802517129?check_suite_focus=true)

at my understanding the tests could not work by using an environment variable 
```cs
Environment.GetEnvironmentVariable("TWITTER_TOKEN")
```

**Comment by Xwilarg** [comment]
Yup you are right, sorry I didn't have the time to look at it yesterday  
I just ran the tests locally and it seems to work fine so I'll merge this, will probably update the nuget package tomorrow or the next day

Thanks for your contribution!

**Pull request merged**
