### PR TITLE
Cancel Tweet Stream

### PR DESCRIPTION
**Pull request by marcogruhl**
Implemented the ability to cancel the tweet stream. Extend comments and tests

### CODE REVIEW

**Comment by Xwilarg** [comment]
Thanks for the PR! I'll launch the tests locally tomorrow

**Comment by marcogruhl** [comment]
The base logic is, if the stream called twice an exception is thrown. In detail its way more complicated. Please look at it. Also check the comments and tests.

**Comment by Xwilarg** [comment]
> The base logic is, if the stream called twice an exception is thrown. In detail its way more complicated. Please look at it. Also check the comments and tests.

Yup I had a quick look at the code and the idea sounds fine to me  
However since it's 2am here I'll look everything more in details tomorrow

**Comment by Xwilarg** [comment]
Well everything looks good to me

**Pull request merged**
