### PR TITLE
Twitter client refactor

### PR DESCRIPTION
**Pull request by karafra**
# :recycle: TwitterClient class refactor

Simple refactor of Client class to use [partial classes](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/partial-classes-and-methods) feature instead of regions

## 👍🏼
* Maintainability :white_check_mark:
* Ability for multiple people to work on same class without merge conflicts :white_check_mark:
* Readability :white_check_mark:

## 👎🏼
* None, as partial classes are compiled together during build :x:

## About improving readability:
As i see your code, you are using sections to differentiate parts of logic. This seems completely fine to me, but IMHO splitting             class into multiple files (if possible) makes much more sense just because it is cleaner and provides much more natural way of        grouping logic together. This also gives possibility of using tree-like structure to group logic together This would be much less readable if used `#region` separation.

### CODE REVIEW

**Comment by Xwilarg** [comment]
Uhm.. I get the idea but I'm just afraid that it might make it harder to find what we are looking for ; I kind of get the idea of moving the parsing part elsewhere but I'm a bit more septical about all the public methods

Also I'm not sure about moving each new file in a separate folder since the Client/ don't have much inside already, I feel like the nesting isn't really necessarly

Globally I'm not against the changes but I would like us to speak a bit more about the whole thing before merging this PR, and hear your opinion of the points mentionned

**Comment by Xwilarg** [comment]
Also looks like the usual convention for partial class naming is ClassName.XXXX.cs so we might want to go with that

(Source:)
 - https://stackoverflow.com/questions/8679582/naming-convention-for-partial-classes-file-names
 - https://stackoverflow.com/questions/1478610/naming-conventions-for-partial-class-files

**Comment by karafra** [comment]
Well of course, not trying to push you anywhere. All this is just how I would do it, and how i think it makes more sense, always open to discussion. About naming convention: as far as I heard from my colleagues it is not very widely used thing and naming files with partial classes is not necessary, but again, willing to rename them.

**Comment by Xwilarg** [comment]
Closing this since there has been no news since a few months, feel free to reopen it if needed

**Pull request closed without merging**
