### PR TITLE
♻️  Client refactor 

### PR DESCRIPTION
**Pull request by karafra**
# :recycle: `TwitterClient` class refactor

Simple refactor of Client class to use [partial classes](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/partial-classes-and-methods) feature instead of regions
 
### 👍🏼
- Maintainability ✅ 
- Ability for multiple people to work on same class without merge conflicts ✅ 
- Readability ✅ 

### 👎🏼
- None, as partial classes are compiled together during build

### CODE REVIEW

**Comment by karafra** [comment]
☝🏼 resolved merge conflicts

**Comment by karafra** [comment]
💚 Failing CI seems to be bug in SonarCube off of which is Codacy based off. SonarCube does not seem to recognize that partials are in different files and therefore are not *gratuitous*

**Comment by Xwilarg** [comment]
Thanks for your PR!

It seems like you have an indentation of 2 space instead of 4 (which is used in the rest of the project), could you please fix that?  
I also think it would be nice if you could use the same commit convention as the others commits (which is based on https://cbea.ms/git-commit/ )

For the changes themselves, I'm not sure making the class partial makes it more clear, but we can speak about that, maybe split this PR into 2?

Also, I can't really try the changes right now but did you check what happens if you call NextTweetStreamAsync with a cancellation token and then call CancelTweetStream afterward?

**Comment by karafra** [comment]
Good Idea, I will close this PR and split it into 2 after work. Fuckup on my side, sorry for that.

To the comments: I will address them in each PR separately so this does not become complete mess 🙏🏼

**Pull request closed without merging**
